### ISSUE TITLE
[BUG] Cannot open recent builds on Windows 10

### ISSUE THREAD

**Issue by LengaJenga** [Qodat/qodat#11]
- [x] I am using the latest version of Qodat

## Bug description

Opening recent builds of Qodat on Windows produces this error:

```
Microsoft Windows [Version 10.0.19043.2364]
(c) Microsoft Corporation. All rights reserved.

E:\Art\Qodat-0.1.8\bin>Qodat.bat
Picked up _JAVA_OPTIONS: -Xmx20G
Error: LinkageError occurred while loading main class stan.qodat.Launcher
        java.lang.UnsupportedClassVersionError: stan/qodat/Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

E:\Art\Qodat-0.1.8\bin>
```

## Steps to reproduce

1. Install https://github.com/Qodat/qodat/actions/runs/3727945323#artifacts
2. Open Bin/Qodat.bat

**Comment by ScoreUnder** [comment]
FWIW the error there means that it requires Java 17 to run, but is running under Java 11. I remember this was discussed in #1, but I guess the question is, should we tell people to update to 17 to use this version or should we be supporting 11?

**Comment by dosier** [comment]
This should be resolved now with the new native app (can download from https://qodat.github.io/qodat/download.html)
